<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-12-21 05:13
=======
# Generated by Django 5.2.8 on 2025-12-16 02:41
>>>>>>> 237ad0bef178cd18770abcb55bbe6b41d1800f3c

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'families',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'icons',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'children',
            },
        ),
        migrations.CreateModel(
            name='Daily_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('child_comment', models.CharField(blank=True, max_length=100)),
                ('photo1_url', models.ImageField(blank=True, null=True, upload_to='daily_logs/')),
                ('photo2_url', models.ImageField(blank=True, null=True, upload_to='daily_logs/')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.child')),
=======
            name='Daily_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('photo1_url', models.ImageField(blank=True, null=True, upload_to='daily_logs/')),
                ('photo2_url', models.ImageField(blank=True, null=True, upload_to='daily_logs/')),
>>>>>>> 237ad0bef178cd18770abcb55bbe6b41d1800f3c
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_logs',
            },
        ),
        migrations.CreateModel(
            name='Family_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, '保護者'), (1, '子ども')], default=0)),
                ('is_admin', models.BooleanField(default=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.family')),
            ],
            options={
                'db_table': 'family_members',
            },
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name='child',
            name='family_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.family_member'),
=======
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.family_member')),
            ],
            options={
                'db_table': 'children',
            },
>>>>>>> 237ad0bef178cd18770abcb55bbe6b41d1800f3c
        ),
        migrations.AddField(
            model_name='user',
            name='family_member',
<<<<<<< HEAD
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.family_member'),
=======
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.family_member'),
>>>>>>> 237ad0bef178cd18770abcb55bbe6b41d1800f3c
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='app.family')),
            ],
            options={
                'db_table': 'invitations',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('color_index', models.PositiveSmallIntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.child')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.family')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='DailyLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.daily_log')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
            ],
            options={
                'db_table': 'daily_log_items',
            },
        ),
        migrations.CreateModel(
            name='ParentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_comments', to='app.daily_log')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parent_comments',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('used', models.BooleanField(default=False)),
                ('user_PasswordReset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='daily_log',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uniq_dailylog_user_date'),
        ),
    ]
