# Generated by Django 5.2.8 on 2025-12-01 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'icons',
            },
        ),
        migrations.CreateModel(
            name='invitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'invitations',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='icon_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.icons'),
            preserve_default=False,
        ),
    ]
