# Generated by Django 5.2.8 on 2025-12-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='daily_log',
            name='uniq_dailylog_user_date',
        ),
        migrations.AddConstraint(
            model_name='daily_log',
            constraint=models.UniqueConstraint(fields=('child', 'date'), name='uniq_dailylog_user_date'),
        ),
    ]
