# Generated by Django 5.2.8 on 2025-12-23 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_daily_log_uniq_dailylog_user_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.icon'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='image_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.family_member'),
        ),
    ]
