# Generated by Django 5.2.8 on 2026-02-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_log',
            name='child_comment',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parentcomment',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
