# Generated by Django 5.2.8 on 2025-12-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_daily_log_uniq_dailylog_user_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='daily_log',
            name='uniq_dailylog_child_date',
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='photo1_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='daily_logs/'),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='photo2_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='daily_logs/'),
        ),
        migrations.AddConstraint(
            model_name='daily_log',
            constraint=models.UniqueConstraint(fields=('child', 'date'), name='uniq_dailylog__date'),
        ),
    ]
