# Generated by Django 5.2.8 on 2026-02-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_child_create_at_child_update_at_daily_log_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='dailylogitem',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='dailylogitem',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='parentcomment',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='parentcomment',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='passwordresettoken',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='passwordresettoken',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
