# Generated by Django 5.2.8 on 2026-02-24 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_create_at_child_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylogitem',
            name='color_index_snapshot',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailylogitem',
            name='item_name_snapshot',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailylogitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.item'),
        ),
    ]
