# Generated by Django 5.2.8 on 2026-02-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_dailylogitem_color_index_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylogitem',
            name='color_index_snapshot',
        ),
        migrations.RemoveField(
            model_name='dailylogitem',
            name='item_name_snapshot',
        ),
    ]
